package com.neusoft.hz.webservice.getparameter;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-22T14:34:55.069+08:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "GetparameterServiceImpl",
                  wsdlLocation = "classpath:wsdl/GetparameterServiceImpl.Wsdl",
                  targetNamespace = "http://hz.neusoft.com")
public class GetparameterServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hz.neusoft.com", "GetparameterServiceImpl");
    public final static QName GetparameterServiceImplPort = new QName("http://hz.neusoft.com", "GetparameterServiceImplPort");
    static {
        URL url = GetparameterServiceImpl.class.getClassLoader().getResource("wsdl/GetparameterServiceImpl.Wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(GetparameterServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GetparameterServiceImpl.Wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetparameterServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetparameterServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetparameterServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetparameterServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetparameterServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetparameterServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GetparameterService
     */
    @WebEndpoint(name = "GetparameterServiceImplPort")
    public GetparameterService getGetparameterServiceImplPort() {
        return super.getPort(GetparameterServiceImplPort, GetparameterService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetparameterService
     */
    @WebEndpoint(name = "GetparameterServiceImplPort")
    public GetparameterService getGetparameterServiceImplPort(WebServiceFeature... features) {
        return super.getPort(GetparameterServiceImplPort, GetparameterService.class, features);
    }

}
