
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.neusoft.hz.webservice.getparameter;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-22T14:34:55.030+08:00
 * Generated source version: 3.3.1
 *
 */

@WebService(
                      serviceName = "GetparameterServiceImpl",
                      portName = "GetparameterServiceImplPort",
                      targetNamespace = "http://hz.neusoft.com",
                      wsdlLocation = "classpath:wsdl/GetparameterServiceImpl.Wsdl",
                      endpointInterface = "com.neusoft.hz.webservice.getparameter.GetparameterService")

public class GetparameterServiceImplPortImpl implements GetparameterService {

    private static final Logger LOG = Logger.getLogger(GetparameterServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.neusoft.hz.webservice.getparameter.GetparameterService#resourceMethod(java.lang.String xmlData)*
     */
    public void resourceMethod(javax.xml.ws.Holder<String> xmlData) throws Exception_Exception   {
        LOG.info("Executing operation resourceMethod");
        System.out.println(xmlData.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
