package com.neusoft.hz.webservice.getparameter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-22T14:34:55.060+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://hz.neusoft.com", name = "GetparameterService")
@XmlSeeAlso({ObjectFactory.class})
public interface GetparameterService {

    @WebMethod
    @RequestWrapper(localName = "resourceMethod", targetNamespace = "http://hz.neusoft.com", className = "com.neusoft.hz.webservice.getparameter.ResourceMethod")
    @ResponseWrapper(localName = "resourceMethodResponse", targetNamespace = "http://hz.neusoft.com", className = "com.neusoft.hz.webservice.getparameter.ResourceMethodResponse")
    public void resourceMethod(
            @WebParam(mode = WebParam.Mode.INOUT, name = "xmlData", targetNamespace = "")
                    javax.xml.ws.Holder<String> xmlData
    ) throws Exception_Exception;
}
