
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.neusoft.hz.webservice;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-23T16:59:09.225+08:00
 * Generated source version: 3.2.7
 *
 */

@WebService(
                      serviceName = "RouterService",
                      portName = "BasicHttpBinding_IRouterService",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "classpath:wsdl/RouterServicesingle.Wsdl",
                      endpointInterface = "com.neusoft.hz.webservice.IRouterService")

public class BasicHttpBinding_IRouterServiceImpl implements IRouterService {

    private static final Logger LOG = Logger.getLogger(BasicHttpBinding_IRouterServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.neusoft.hz.webservice.IRouterService#runService(java.lang.String serviceType, java.lang.String context, java.lang.String inMsg, java.lang.String outMsg, java.lang.Integer runServiceResult)*
     */
    public void runService(String serviceType, String context, String inMsg, javax.xml.ws.Holder<String> outMsg, javax.xml.ws.Holder<Integer> runServiceResult) {
        LOG.info("Executing operation runService");
        System.out.println(serviceType);
        System.out.println(context);
        System.out.println(inMsg);
        System.out.println(outMsg.value);
        try {
            Integer runServiceResultValue = null;
            runServiceResult.value = runServiceResultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
