package com.neusoft.hz.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-23T16:59:09.332+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IRouterService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRouterService {

    @WebMethod(operationName = "RunService", action = "http://tempuri.org/IRouterService/RunService")
    @Action(input = "http://tempuri.org/IRouterService/RunService", output = "http://tempuri.org/IRouterService/RunServiceResponse")
    @RequestWrapper(localName = "RunService", targetNamespace = "http://tempuri.org/", className = "com.neusoft.hz.webservice.RunService")
    @ResponseWrapper(localName = "RunServiceResponse", targetNamespace = "http://tempuri.org/", className = "com.neusoft.hz.webservice.RunServiceResponse")
    public void runService(
            @WebParam(name = "serviceType", targetNamespace = "http://tempuri.org/")
                    String serviceType,
            @WebParam(name = "context", targetNamespace = "http://tempuri.org/")
                    String context,
            @WebParam(name = "inMsg", targetNamespace = "http://tempuri.org/")
                    String inMsg,
            @WebParam(mode = WebParam.Mode.INOUT, name = "outMsg", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<String> outMsg,
            @WebParam(mode = WebParam.Mode.OUT, name = "RunServiceResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<Integer> runServiceResult
    );
}
