package com.neusoft.hz.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-23T16:59:09.345+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "RouterService",
                  wsdlLocation = "classpath:wsdl/RouterServicesingle.Wsdl",
                  targetNamespace = "http://tempuri.org/")
public class RouterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RouterService");
    public final static QName BasicHttpBindingIRouterService = new QName("http://tempuri.org/", "BasicHttpBinding_IRouterService");
    static {
        URL url = RouterService.class.getClassLoader().getResource("wsdl/RouterServicesingle.Wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RouterService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/RouterServicesingle.Wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RouterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RouterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RouterService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RouterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RouterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RouterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IRouterService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRouterService")
    public IRouterService getBasicHttpBindingIRouterService() {
        return super.getPort(BasicHttpBindingIRouterService, IRouterService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRouterService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRouterService")
    public IRouterService getBasicHttpBindingIRouterService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIRouterService, IRouterService.class, features);
    }

}
